import { SOURCES } from "./event";
import type { City, ContactTimes } from "./types";

/** Ninguno de los cinco contactos verificado todavía. */
const NO_CONTACTS: ContactTimes = {
  partialStart: null,
  totalityStart: null,
  maximum: null,
  totalityEnd: null,
  partialEnd: null,
};

/**
 * Ciudades y municipios cubiertos por la red.
 *
 * Las duraciones marcadas como "reported" proceden de las tablas publicadas por el
 * IGN y recogidas por prensa; están pendientes de contrastar campo a campo contra
 * la tabla oficial completa, que es la primera tarea del agente `eclipse-data`.
 * Las marcadas como "pending" no llevan número y la UI lo dice explícitamente.
 */
export const CITIES: City[] = [
  {
    slug: "ceuta",
    name: "Ceuta",
    province: "Ceuta",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 35.8894,
    lon: -5.3213,
    population: 83517,
    hook: "El mejor punto de toda España: casi cinco minutos de totalidad, el máximo del país.",
    circumstances: {
      inTotality: true,
      totalitySeconds: 288, // 4m 48s
      contacts: { ...NO_CONTACTS, totalityStart: "10:45:00", totalityEnd: "10:49:48" },
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "reported",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "melilla",
    name: "Melilla",
    province: "Melilla",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 35.2923,
    lon: -2.9381,
    population: 86261,
    hook: "Más de cuatro minutos y medio de totalidad con el Sol muy alto sobre el Mediterráneo.",
    circumstances: {
      inTotality: true,
      totalitySeconds: 273, // 4m 33s
      contacts: { ...NO_CONTACTS, totalityStart: "10:48:00" },
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "reported",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "algeciras",
    name: "Algeciras",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.1275,
    lon: -5.4536,
    population: 123078,
    hook: "El mejor punto de la Península: 4 minutos y 26 segundos, más que Cádiz y Málaga juntas.",
    circumstances: {
      inTotality: true,
      totalitySeconds: 266, // 4m 26s
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "reported",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "cadiz",
    name: "Cádiz",
    nameEn: "Cadiz",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.5271,
    lon: -6.2886,
    population: 110616,
    hook: "Una de las dos únicas capitales de provincia dentro de la franja de totalidad.",
    circumstances: {
      inTotality: true,
      totalitySeconds: 173, // 2m 53s
      contacts: { ...NO_CONTACTS, totalityStart: "10:45:00" },
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "reported",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "malaga",
    name: "Málaga",
    nameEn: "Malaga",
    province: "Málaga",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.7213,
    lon: -4.4214,
    population: 586384,
    hook: "Capital dentro de la franja, pero cerca del borde: menos de dos minutos de totalidad.",
    circumstances: {
      inTotality: true,
      totalitySeconds: 107, // 1m 47s
      contacts: { ...NO_CONTACTS, totalityStart: "10:48:00" },
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "reported",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "tarifa",
    name: "Tarifa",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.0143,
    lon: -5.6044,
    population: 18775,
    hook: "El punto más al sur de la Península, en pleno eje de la franja y con horizonte marino.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "marbella",
    name: "Marbella",
    province: "Málaga",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.5101,
    lon: -4.8824,
    population: 156295,
    hook: "Totalidad en la Costa del Sol occidental, con la mayor oferta hotelera de la franja.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "estepona",
    name: "Estepona",
    province: "Málaga",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.4276,
    lon: -5.1448,
    population: 78060,
    hook: "Costa del Sol con totalidad más larga que Málaga capital por estar más al oeste.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "la-linea-de-la-concepcion",
    name: "La Línea de la Concepción",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.1611,
    lon: -5.3486,
    population: 62864,
    hook: "Junto al Peñón y a pocos kilómetros del centro de la franja.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "conil-de-la-frontera",
    name: "Conil de la Frontera",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.2769,
    lon: -6.0894,
    population: 22505,
    hook: "Playas abiertas al Atlántico y cielos despejados en agosto.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "vejer-de-la-frontera",
    name: "Vejer de la Frontera",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.2529,
    lon: -5.9663,
    population: 12905,
    hook: "Pueblo blanco en alto: uno de los mejores miradores naturales de la franja.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "barbate",
    name: "Barbate",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.1922,
    lon: -5.9223,
    population: 22558,
    hook: "Costa de la Luz, con el cabo de Trafalgar como escenario de observación.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "chiclana-de-la-frontera",
    name: "Chiclana de la Frontera",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.4194,
    lon: -6.1464,
    population: 87543,
    hook: "La Barrosa y una de las mayores capacidades de alojamiento de la provincia.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "san-roque",
    name: "San Roque",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.2103,
    lon: -5.3844,
    population: 32118,
    hook: "Campo de Gibraltar, en el corazón de la franja de máxima duración peninsular.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "gibraltar",
    name: "Gibraltar",
    province: "Gibraltar",
    country: "GI",
    timeZone: "Europe/Gibraltar",
    lat: 36.1408,
    lon: -5.3536,
    population: 32688,
    hook: "El Peñón, dentro de la franja y con visitantes llegando desde el Reino Unido.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
  {
    slug: "jerez-de-la-frontera",
    name: "Jerez de la Frontera",
    province: "Cádiz",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.6866,
    lon: -6.1361,
    population: 213231,
    hook: "Aeropuerto propio y la mayor ciudad de la provincia: puerta de entrada a la franja.",
    circumstances: {
      // Jerez queda en la mitad norte de la provincia, cerca del borde de la franja.
      // Hasta confirmar el municipio en la lista oficial no afirmamos totalidad.
      inTotality: false,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.juntaAndalucia],
    },
  },
  {
    slug: "motril",
    name: "Motril",
    province: "Granada",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.7448,
    lon: -3.5188,
    population: 62290,
    hook: "Costa Tropical granadina, en el tramo sur de la provincia que entra en la franja.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.juntaAndalucia],
    },
  },
  {
    slug: "adra",
    name: "Adra",
    province: "Almería",
    country: "ES",
    timeZone: "Europe/Madrid",
    lat: 36.7487,
    lon: -3.0207,
    population: 25523,
    hook: "Uno de los diez municipios almerienses que alcanzan la totalidad.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.juntaAndalucia],
    },
  },
  {
    slug: "tanger",
    name: "Tánger",
    nameEn: "Tangier",
    province: "Tánger-Tetuán-Alhucemas",
    country: "MA",
    timeZone: "Africa/Casablanca",
    lat: 35.7595,
    lon: -5.834,
    population: 1275428,
    hook: "Al otro lado del Estrecho, con totalidad larga y una hora local distinta a la española.",
    circumstances: {
      inTotality: true,
      totalitySeconds: null,
      contacts: NO_CONTACTS,
      sunAltitudeDeg: null,
      magnitude: null,
      kmToCenterline: null,
      confidence: "pending",
      sources: [SOURCES.ign],
    },
  },
];

export const CITIES_BY_SLUG = new Map(CITIES.map((c) => [c.slug, c]));

export function getCity(slug: string): City | undefined {
  return CITIES_BY_SLUG.get(slug);
}

/** Ciudades con totalidad confirmada, de más larga a más corta; las pendientes al final. */
export function citiesByTotality(): City[] {
  return [...CITIES]
    .filter((c) => c.circumstances.inTotality)
    .sort((a, b) => (b.circumstances.totalitySeconds ?? -1) - (a.circumstances.totalitySeconds ?? -1));
}

/** "4 min 48 s" a partir de segundos. Devuelve null si no hay dato verificado. */
export function formatDuration(seconds: number | null): string | null {
  if (seconds === null) return null;
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return s === 0 ? `${m} min` : `${m} min ${s} s`;
}
